export enum UpdateReturnValuesModes {
    RETURN_NOTHING                  = 'NONE',
    ALL_ATTRIBUTES_BEFORE_UPDATE    = 'ALL_OLD',
    UPDATED_ATTRIBUTES_BEFORE_UPDATE= 'UPDATED_OLD',
    ALL_ATTRIBUTES_AFTER_UPDATE     = 'ALL_NEW',
    UPDATED_ATTRIBUTES_AFTER_UPDATE = 'UPDATED_NEW'
}
